collections:
  music:
    output: true
    permalink: /music/:path/
  books:
    output: true
    permalink: /books/:path/
  lists:
    output: true
    permalink: /lists/:name/
  blog:
    output: true
    permalink: /blog/:path/
  photography:
    output: true
    permalink: /photography/:path/
  world:
    output: true
    permalink: /world/:path/
  climbing:
    output: true
    permalink: /climbing/:path/
